% Some initialization stuff...
sampleRate = 2e4;
sampleInterval = 1 / sampleRate;

% Load the data.
load('data/raw-lfp-data.mat');

load('data/theta-spect-250ms-window.mat', 'spect', 'frequencies', 'times');
thetaSpect = spect;
thetaFrequencies = frequencies;
thetaTimes = times;

load('data/spect-50ms-window.mat', 'spect', 'frequencies', 'times', 'windowStep');
load('data/computed-data-orig.mat', 'spw');

% Compute the signals used to detect ripples.
filterRadius = 0.025;
smth = @(v, w) conv(v, gaussfilt(2 * filterRadius * w + 1), 'same');
sampleRate2 = 1 / windowStep;

filter   = gaussfilt(2 * filterRadius * sampleRate + 1);
timeline = (0 : length(lfpMain) - 1) / sampleRate;

sharpWave      = zscore(computeSharpWave(lfpLow, lfpHigh, filter));
sharpWaveDiff  = [0; diff(sharpWave)] * sampleRate;
sharpWaveDiff2 = smth([0; diff(sharpWaveDiff)] * sampleRate, sampleRate);
rippleWave     = smth(zscore(mean(spect, 1)), sampleRate2);
thetaWave      = smth(zscore(mean(thetaSpect, 1)), sampleRate2);

lfpMainTs        = timeseries(lfpMain, timeline);
sharpWaveTs      = timeseries(sharpWave, timeline);
sharpWaveDiffTs  = timeseries(sharpWaveDiff, timeline);
sharpWaveDiff2Ts = timeseries(sharpWaveDiff2, timeline);
rippleWaveTs     = timeseries(rippleWave', times);
thetaWaveTs      = timeseries(thetaWave', thetaTimes);

ripplesOrig      = [spw.startT', spw.peakT', spw.endT'] / sampleRate;
lfpTriple        = [lfpLow - mean(lfpLow), lfpHigh - mean(lfpHigh), lfpMain - mean(lfpMain)];
lfpTripleTs      = timeseries(lfpTriple, timeline);
lfpTripleTs.Name = 'LFP Data';
rippleSpectTs    = timeseries(spect', times);
thetaSpectTs     = timeseries(thetaSpect', thetaTimes);

%%
lfpFiltered = FilterLFP(         ...
    [lfpMainTs.Time, lfpMainTs.Data] ,            ...
    'passband'      , [90, 180], ...
    'filter'        , 'fir1',    ...
    'order'         , 500,       ...
    'nyquist'       , 1e4);

tmp = @(v) v / sum(v);
lfpPower = zscore(conv(lfpFiltered(:, 2).^2, tmp(ones(2 * 0.015 * sampleRate + 1)), 'same'));
lfpPowerTs = timeseries(lfpPower, lfpFiltered(:, 1));

%% Find the ripples

clear DetectRipples
clc;

minSharpWavePeak = 3;
minSharpWave = 1;
minSharpWaveDiff = 160;
% minSharpWaveDiff2 = 0.3e4;

minRippleWavePeak = 0;
minRippleWave = -Inf;

maxThetaDuringRipple = 3;

[ripples, ~, ~] = DetectRipples(lfpMainTs,        ...
    'sharpWave'            , sharpWaveTs,         ...
    'minSharpWavePeak'     , minSharpWavePeak,    ...
    'minSharpWave'         , minSharpWave,        ...
                                                  ...
    'sharpWaveDiff'        , sharpWaveDiffTs,     ...
    'minSharpWaveDiff'     , minSharpWaveDiff,    ...
    ...'sharpWaveDiff2'        , sharpWaveDiff2Ts,     ...
    ...'minSplitPoint'     , minSharpWaveDiff2,    ...
                                                  ...
    'rippleWave'           , rippleWaveTs,        ...
    'minRippleWavePeak'    , minRippleWavePeak,   ...
    'minRippleWave'        , minRippleWave,       ...
                                                  ...
    'thetaWave'            , thetaWaveTs,         ...
    'maxThetaDuringRipple' , maxThetaDuringRipple ...
    );

%% Plot the ripples

clear plotRipples

plotRipples(                                      ...
    'ripples1'          , ripples,                ...
    'title1'            , 'My Ripple Events',     ...
                                                  ...
    'ripples2'          , ripplesOrig,            ...
    'title2'            , 'Eva''s Ripple Events', ...
                                                  ...
    'lfpTriple'         , lfpTripleTs,            ...
                                                  ...
    'sharpWave'         , sharpWaveTs,            ...
    'minSharpWavePeak'  , minSharpWavePeak,       ...
    'minSharpWave'      , minSharpWave,           ...
                                                  ...
    'sharpWaveDiff'     , sharpWaveDiffTs,        ...
    'minSharpWaveDiff'  , minSharpWaveDiff,       ...
                                                  ...
    'rippleSpect'       , rippleSpectTs,          ...
    'rippleFreqs'       , frequencies,            ...
    'rippleWave'        , rippleWaveTs,           ...
    'minRippleWavePeak' , minRippleWavePeak,      ...
    'minRippleWave'     , minRippleWave,          ...
                                                  ...
    'thetaSpect'        , thetaSpectTs,           ...
    'thetaFreqs'        , thetaFrequencies,       ...
    'thetaWave'         , thetaWaveTs,            ...
    'maxThetaWave'      , maxThetaDuringRipple,   ...
                                                  ...
    'eventsToPlot'      , 1:10                   ...
    );

%%
