% Some initialization stuff...
sampleRate = 2e4;
sampleInterval = 1 / sampleRate;

% Load the data.
load('data/raw-lfp-data.mat');

load('data/theta-spect-250ms-window.mat', 'spect', 'frequencies', 'times');
thetaSpect = spect;
thetaFrequencies = frequencies;
thetaTimes = times;

load('data/spect-50ms-window.mat', 'spect', 'frequencies', 'times', 'windowStep');
load('data/computed-data-orig.mat', 'spw');

% Compute the signals used to detect ripples.
filterRadius = 0.025;
smth = @(v, w) conv(v, gaussfilt(2 * filterRadius * w + 1), 'same');
sampleRate2 = 1 / windowStep;

filter   = gaussfilt(2 * filterRadius * sampleRate + 1);
timeline = (0 : length(lfpMain) - 1) / sampleRate;

sharpWave      = smth(zscore(computeSharpWave(lfpLow, lfpHigh, filter)), sampleRate);
rippleWave     = smth(zscore(mean(spect, 1)'), sampleRate2);

sharpWaveTs      = timeseries(sharpWave, timeline);
rippleWaveTs     = timeseries(rippleWave', times);

sharpWaveTs = resample(sharpWaveTs, times);
sharpWave = sharpWaveTs.Data;
startTime = times(1);

% For plotting...
ripplesOrig      = [spw.startT', spw.peakT', spw.endT'] / sampleRate;
lfpTriple        = [lfpLow - mean(lfpLow), lfpHigh - mean(lfpHigh), lfpMain - mean(lfpMain)];
lfpTripleTs      = timeseries(lfpTriple, timeline);
lfpTripleTs.Name = 'LFP Data';
rippleSpectTs    = timeseries(spect', times);

firstDerivative = [0; diff(sharpWave)] * sampleRate2;
firstDerivativeTs = timeseries(firstDerivative, times);
secondDerivative = [0; diff(firstDerivative)] * sampleRate2;
secondDerivativeTs = timeseries(secondDerivative, times);

% %%
% lfpFiltered = FilterLFP(         ...
%     [lfpMainTs.Time, lfpMainTs.Data] ,            ...
%     'passband'      , [90, 180], ...
%     'filter'        , 'fir1',    ...
%     'order'         , 500,       ...
%     'nyquist'       , 1e4);
%
% tmp = @(v) v / sum(v);
% lfpPower = zscore(conv(lfpFiltered(:, 2).^2, tmp(ones(2 * 0.015 * sampleRate + 1)), 'same'));
% lfpPowerTs = timeseries(lfpPower, lfpFiltered(:, 1));

%% Find the ripples

clear DetectRipples
clc;

minSharpWavePeak = 2; %3;
minSharpWave = 1;
minFirstDerivative = 100; %120; %160;
minSecondDerivative = 0.75e4;

minRippleWavePeak = 0;
minRippleWave = -Inf;

[ripples, ~, ~] = DetectRipples(sharpWave, rippleWave, ...
    'sampleRate'           , sampleRate2,              ...
    ...'duration'             , [0.025, 0.05],            ...
                                                       ...
    'minSharpWavePeak'     , minSharpWavePeak,         ...
    'minSharpWave'         , minSharpWave,             ...
                                                       ...
    'minFirstDerivative'   , minFirstDerivative,       ...
    'minSecondDerivative'  , minSecondDerivative,      ...
                                                       ...
    'minRippleWavePeak'    , minRippleWavePeak,        ...
    'minRippleWave'        , minRippleWave             ...
    );

ripples = ripples + startTime;

%% Plot the ripples

clc;
close('all');
clear plotRipples

plotRipples(                                        ...
    'ripples1'            , ripples,                ...
    'title1'              , 'My Ripple Events',     ...
                                                    ...
    'ripples2'            , ripplesOrig,            ...
    'title2'              , 'Eva''s Ripple Events', ...
                                                    ...
    'lfpTriple'           , lfpTripleTs,            ...
                                                    ...
    'sharpWave'           , sharpWaveTs,            ...
    'minSharpWavePeak'    , minSharpWavePeak,       ...
    'minSharpWave'        , minSharpWave,           ...
                                                    ...
    'firstDerivative'     , firstDerivativeTs,      ...
    'minFirstDerivative'  , minFirstDerivative,     ...
                                                    ...
    'secondDerivative'    , secondDerivativeTs,     ...
    'minSecondDerivative' , minSecondDerivative,    ...
                                                    ...
    'rippleSpect'         , rippleSpectTs,          ...
    'rippleFreqs'         , frequencies,            ...
    'rippleWave'          , rippleWaveTs,           ...
    'minRippleWavePeak'   , minRippleWavePeak,      ...
    'minRippleWave'       , minRippleWave,          ...
                                                    ...
    'eventsToPlot'        , 1:30                    ...
    );

%%
