% Some initialization stuff...
sampleRate = 2e4;
sampleInterval = 1 / sampleRate;

% Load the data.
load('data/raw-lfp-data.mat');
load('data/spect-1250Hz-100ms-window.mat', 'spect', 'frequencies', 'times', 'windowStep');
load('data/computed-data-orig.mat', 'spw');

% Compute the signals used to detect ripples.
filterRadius = 0.024;
smth = @(v, w) conv(v, gaussfilt(2 * filterRadius * w + 1), 'same');
sampleRate2 = 1 / windowStep;

timeline = (0 : length(lfpMain) - 1) / sampleRate;

sharpWave      = smth(computeSharpWave(lfpLow, lfpHigh), sampleRate);
rippleWaveTs = computeRippleWave(spect, 'dataIsSpect', true, 'spectTimes', times);
rippleWave     = smth(rippleWaveTs.Data, sampleRate2);

sharpWaveTs      = timeseries(sharpWave, timeline);
rippleWaveTs     = timeseries(rippleWave', times);

sharpWaveTs = resample(sharpWaveTs, times);
sharpWave = sharpWaveTs.Data;
startTime = times(1);

% For plotting...
ripplesOrig      = [spw.startT', spw.peakT', spw.endT'] / sampleRate;
lfpTriple        = [lfpLow - mean(lfpLow), lfpHigh - mean(lfpHigh), lfpMain - mean(lfpMain)];
lfpTripleTs      = timeseries(lfpTriple, timeline);
lfpTripleTs.Name = 'LFP Data';
rippleSpectTs    = timeseries(spect', times);

firstDerivative = [0; diff(sharpWave)] * sampleRate2;
firstDerivative = firstDerivative / std(firstDerivative);
firstDerivativeTs = timeseries(firstDerivative, times);

secondDerivative = [0; diff(firstDerivative)] * sampleRate2;
secondDerivative = secondDerivative / std(secondDerivative);
secondDerivativeTs = timeseries(secondDerivative, times);

% %%
% lfpFiltered = FilterLFP(         ...
%     [lfpMainTs.Time, lfpMainTs.Data] ,            ...
%     'passband'      , [90, 180], ...
%     'filter'        , 'fir1',    ...
%     'order'         , 500,       ...
%     'nyquist'       , 1e4);
%
% tmp = @(v) v / sum(v);
% lfpPower = zscore(conv(lfpFiltered(:, 2).^2, tmp(ones(2 * 0.015 * sampleRate + 1)), 'same'));
% lfpPowerTs = timeseries(lfpPower, lfpFiltered(:, 1));

%% Find the ripples

clear DetectRipples

minSharpWavePeak = 2;
minSharpWave = 1.6;
minFirstDerivative = 2.75;
minSecondDerivative = 2.9;

minRippleWavePeak = 0;
minRippleWave = -Inf;

ripples = DetectRipples(sharpWave, rippleWave, ...
    'sampleRate'           , sampleRate2,              ...
    ...'duration'             , [0.025, 0.05],            ...
                                                       ...
    'minSharpWavePeak'     , minSharpWavePeak,         ...
    'minSharpWave'         , minSharpWave,             ...
                                                       ...
    'minFirstDerivative'   , minFirstDerivative,       ...
    'minSecondDerivative'  , minSecondDerivative,      ...
                                                       ...
    'minRippleWavePeak'    , minRippleWavePeak,        ...
    'minRippleWave'        , minRippleWave             ...
    );

ripples = ripples + startTime;

%% Plot the ripples

clc;
close('all');
clear plotRipples

plotRipples(                                        ...
    'ripples1'            , ripples,                ...
    'title1'              , 'My Ripple Events',     ...
                                                    ...
    'ripples2'            , ripplesOrig,            ...
    'title2'              , 'Eva''s Ripple Events', ...
                                                    ...
    'lfpTriple'           , lfpTripleTs,            ...
                                                    ...
    'sharpWave'           , sharpWaveTs,            ...
    'minSharpWavePeak'    , minSharpWavePeak,       ...
    'minSharpWave'        , minSharpWave,           ...
                                                    ...
    'firstDerivative'     , firstDerivativeTs,      ...
    'minFirstDerivative'  , minFirstDerivative,     ...
                                                    ...
    'secondDerivative'    , secondDerivativeTs,     ...
    'minSecondDerivative' , minSecondDerivative,    ...
                                                    ...
    'rippleSpect'         , rippleSpectTs,          ...
    'rippleFreqs'         , frequencies,            ...
    'rippleWave'          , rippleWaveTs,           ...
    'minRippleWavePeak'   , minRippleWavePeak,      ...
    'minRippleWave'       , minRippleWave,          ...
                                                    ...
    'eventsToPlot'        , 1:41                    ...
    );

%%
