% cellSeqs = getRippleSequences(this, varargin)
function cellSeqs = getRippleSequences(this, varargin)
    cellSeqs = [ getRippleSequences(this.pre, varargin{:}); ...
                 getRippleSequences(this.musc, varargin{:}); ...
                 getRippleSequences(this.post, varargin{:})  ...
               ];
end
