% mtxRipples = getRipples(this, vRippleNums)
function mtxRipples = getRipples(this, vRippleNums)
    if nargin == 2
        mtxRipples = [ getRipples(this.pre, vRippleNums); ...
                       getRipples(this.musc, vRippleNums); ...
                       getRipples(this.post, vRippleNums) ...
                     ];
    else
        mtxRipples = [ getRipples(this.pre); ...
                       getRipples(this.musc); ...
                       getRipples(this.post) ...
                     ];
    end
end